Fixes

diff --git a/.github/workflows/helm-ci.yaml b/.github/workflows/helm-ci.yaml
--- a/.github/workflows/helm-ci.yaml
+++ b/.github/workflows/helm-ci.yaml
@@ -12,48 +12,30 @@ jobs:
   lint-chart:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - name: Set up Helm
-        uses: azure/setup-helm@v3
-        with:
-          version: v3.10.0
+      - uses: azure/setup-helm@v3
 
       - uses: actions/setup-python@v4
         with:
           python-version: '3.9'
           check-latest: true
 
-      - name: Set up chart-testing
-        uses: helm/chart-testing-action@v2.3.1
+      - uses: helm/chart-testing-action@main
 
       - name: Run chart-testing (list-changed)
-        id: list-changed
-        run: |
-          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
-          if [[ -n "$changed" ]]; then
-            echo "::set-output name=changed::true"
-          fi
+        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}
 
       - name: Run chart-testing (lint)
         run: ct lint --target-branch ${{ github.event.repository.default_branch }}
-
-      - name: Create kind cluster
-        uses: helm/kind-action@v1.4.0
-        if: steps.list-changed.outputs.changed == 'true'
-
-      - name: Run chart-testing (install)
-        run: ct install
 
   lint-docs:
     runs-on: ubuntu-latest
     needs: lint-chart
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
@@ -83,8 +65,7 @@ jobs:
           - 1.17.17
           - 1.16.15
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
@@ -99,13 +80,12 @@ jobs:
       - lint-chart
       - lint-docs
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
       - name: Run kube-score
-        run: .github/kube-score.sh || exit 0
+        run: .github/kube-score.sh || exit 0 #To avoid failing the build
 
   install-chart:
     name: install-chart
@@ -133,18 +113,17 @@ jobs:
           - 1.17.17
           - 1.16.15
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - name: Create kind ${{ matrix.k8s }} cluster
-        uses: helm/kind-action@main
+      - uses: helm/kind-action@main
         with:
           node_image: kindest/node:${{ matrix.k8s }}
 
+      - uses: helm/chart-testing-action@main
+
+      - uses: helm/kind-action@v${{ matrix.k8s }}
+
       - name: Run chart-testing (install)
-        uses: helm/chart-testing-action@main
-        with:
-          command: install
-          config: .github/ct.yaml
+        run: ct install
